TRUNCATE TABLE `county_regions`;

INSERT INTO `county_regions` (`id`, `name`, `short_name`, `country_id`) VALUES
(1, 'Alaska', 'Alaska', 1),
(2, 'Alabama', 'Alabama', 1),
(3, 'Outside US', 'Outside US', 1),
(4, 'Arkansas', 'Arkansas', 1),
(5, 'Arizona', 'Arizona', 1),
(6, 'California', 'California', 1),
(7, 'Colorado', 'Colorado', 1),
(8, 'Connecticut', 'Connecticut', 1),
(9, 'District of Columbia', 'District of Columbia', 1),
(10, 'Delaware', 'Delaware', 1),
(11, 'Florida', 'Florida', 1),
(12, 'Georgia', 'Georgia', 1),
(13, 'Hawaii', 'Hawaii', 1),
(14, 'Iowa', 'Iowa', 1),
(15, 'Idaho', 'Idaho', 1),
(16, 'Illinois', 'Illinois', 1),
(17, 'Indiana', 'Indiana', 1),
(18, 'Kansas', 'Kansas', 1),
(19, 'Kentucky', 'Kentucky', 1),
(20, 'Louisiana', 'Louisiana', 1),
(21, 'Massachusetts', 'Massachusetts', 1),
(22, 'Maryland', 'Maryland', 1),
(23, 'Maine', 'Maine', 1),
(24, 'Michigan', 'Michigan', 1),
(25, 'Minnesota', 'Minnesota', 1),
(26, 'Missouri', 'Missouri', 1),
(27, 'Mississippi', 'Mississippi', 1),
(28, 'Montana', 'Montana', 1),
(29, 'North Carolina', 'North Carolina', 1),
(30, 'North Dakota', 'North Dakota', 1),
(31, 'Nebraska', 'Nebraska', 1),
(32, 'New Hampshire', 'New Hampshire', 1),
(33, 'New Jersey', 'New Jersey', 1),
(34, 'New Mexico', 'New Mexico', 1),
(35, 'Nevada', 'Nevada', 1),
(36, 'New York', 'New York', 1),
(37, 'Ohio', 'Ohio', 1),
(38, 'Oklahoma', 'Oklahoma', 1),
(39, 'Oregon', 'Oregon', 1),
(40, 'Pennsylvania', 'Pennsylvania', 1),
(41, 'Rhode Island', 'Rhode Island', 1),
(42, 'South Carolina', 'South Carolina', 1),
(43, 'South Dakota', 'South Dakota', 1),
(44, 'Tennessee', 'Tennessee', 1),
(45, 'Texas', 'Texas', 1),
(46, 'Utah', 'Utah', 1),
(47, 'Virginia', 'Virginia', 1),
(48, 'Vermont', 'Vermont', 1),
(49, 'Washington', 'Washington', 1),
(50, 'Wisconsin', 'Wisconsin', 1),
(51, 'West Virginia', 'West Virginia', 1),
(52, 'Wyoming', 'Wyoming', 1),
(53, 'Alberta', 'Alberta', 2),
(54, 'British Columbia', 'British Columbia', 2),
(55, 'Manitoba', 'Manitoba', 2),
(56, 'New Brunswick', 'New Brunswick', 2),
(57, 'Newfoundland', 'Newfoundland', 2),
(58, 'Newfoundland_Labrador', 'Newfoundland_Labrador', 2),
(59, 'Northwest Territories', 'Northwest Territories', 2),
(60, 'Nova Scotia', 'Nova Scotia', 2),
(61, 'Nunavut', 'Nunavut', 2),
(62, 'Ontario', 'Ontario', 2),
(63, 'Prince Edward Island', 'Prince Edward Island', 2),
(64, 'Quebec', 'Quebec', 2),
(65, 'Saskatchewan', 'Saskatchewan', 2),
(66, 'Yukon', 'Yukon', 2),
(67, 'Yukon Territory', 'Yukon Territory', 2);
